ci: workflow fixes
* bump.yml remove default bump-command
* rebase.yml add Validate step
* fast-forward.yml improve logging

diff --git a/.github/workflows/rebase.yml b/.github/workflows/rebase.yml
--- a/.github/workflows/rebase.yml
+++ b/.github/workflows/rebase.yml
@@ -23,6 +23,12 @@ jobs:
     runs-on: ubuntu-22.04
     environment: ${{ inputs.environment }}
     steps:
+      - name: Validate
+      if: github.event.inputs.target-ref == 'master'
+      run: |
+        echo "Target branch cannot be master"
+        exit 1
+
       - name: Create deployooor app token
         uses: actions/create-github-app-token@v1
         id: app-token
