ci: fix validate step

diff --git a/.github/workflows/rebase.yml b/.github/workflows/rebase.yml
--- a/.github/workflows/rebase.yml
+++ b/.github/workflows/rebase.yml
@@ -24,10 +24,10 @@ jobs:
     environment: ${{ inputs.environment }}
     steps:
       - name: Validate
-      if: github.event.inputs.target-ref == 'master'
-      run: |
-        echo "Target branch cannot be master"
-        exit 1
+        if: github.event.inputs.target-ref == 'master'
+        run: |
+          echo "Target branch cannot be master"
+          exit 1
 
       - name: Create deployooor app token
         uses: actions/create-github-app-token@v1
